In [1]:
import torch
import numpy as np

In [2]:
#Create tensor from list
tensor_list=torch.tensor([1,1,1])
tensor_list

tensor([1, 1, 1])

In [6]:
#Create tensor from numpy array
nparray=np.array([[1,1,1],[2,2,2],[3,3,3]])
tensor_array=torch.tensor(nparray)
tensor_array

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [7]:
#Create tensor with zeros and ones
tensor_zeros=torch.zeros(2,2)
tensor_ones=torch.ones(2,2)
print(tensor_zeros)
print(tensor_ones)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [8]:
#Create random tensors
random_tensor=torch.rand(3,3)  #Uniform Distribution between 0 and 1
normal_tensor=torch.randn(3,3) #Normal Distribution with mean 0 and variance 1
print(random_tensor)
print(normal_tensor)

tensor([[0.4243, 0.2358, 0.0999],
        [0.3765, 0.5668, 0.0250],
        [0.9201, 0.0734, 0.5843]])
tensor([[ 1.7463, -1.6615,  1.5348],
        [-1.7693, -1.1394, -0.2085],
        [ 0.6564,  0.0128,  0.3316]])


In [12]:
#Specify its type
tensor_int=torch.tensor([1,1,1],dtype=torch.int)
tensor_float=torch.tensor([1.5,1.7,1.9],dtype=torch.float32)
print(tensor_int)
print(tensor_float)

tensor([1, 1, 1], dtype=torch.int32)
tensor([1.5000, 1.7000, 1.9000])


In [13]:
#Create tensors using GPU if it is avaliable
tensor_gpu=torch.tensor([1,1,1],device='cuda')
print(tensor_gpu)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx