In [1]:
#Import pytorch
import torch

In [4]:
#Creating 2 tensors
tensor1=torch.rand(3,3)
tensor2=torch.rand(3,3)

In [5]:
#Multiply the 2 tensor by using matmult function which refers to Matrix Multiplication
result=torch.matmul(tensor1,tensor2)

In [11]:
#Print tensor1, tensor2, Result
print(f"Tensor 1 is\n {tensor1}")
print(f"Tensor 2 is\n {tensor2}")
print(f"Result is\n {result}")


Tensor 1 is
 tensor([[0.9315, 0.1864, 0.3963],
        [0.7610, 0.8195, 0.6769],
        [0.7177, 0.9490, 0.0435]])
Tensor 2 is
 tensor([[0.7171, 0.3627, 0.1161],
        [0.4307, 0.6883, 0.7812],
        [0.1600, 0.1889, 0.2575]])
Result is
 tensor([[0.8117, 0.5410, 0.3557],
        [1.0070, 0.9680, 0.9028],
        [0.9304, 0.9217, 0.8359]])


In [14]:
if torch.cuda.is_available():
  tersor1=tensor1.to("cuda")
  tensor2=tensor2.to("cuda")
  result=torch.matmul(tensor1,tensor2)
  print(f"Result is\n {result}")
else:
  print("CUDA is not available")

CUDA is not available
